login_demo/app/urls.py
from django.urls import path
from app import views
app_name='app'
urlpatterns=[
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
]

login_demo/login_demo/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
import app
from app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('app/',include('app.urls')),
    path('logout/',views.user_logout,name="logout"),
    path('wish/',views.wish,name='wish'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

login_demo/app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class User_data(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    webpage=models.URLField(blank=True)
    profile_pic=models.ImageField(upload_to='user',blank=True)

    def __str__(self):
        return self.user.username
    

login_demo/app/forms.py
from app.models import *
from django import forms
class User_Form(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=('username',"email",'password')
        
class User_data_form(forms.ModelForm):
    class Meta:
        model=User_data
        fields=('webpage',"profile_pic")

login_demo/app/views.py
from django.shortcuts import render
from app import forms 

from django.contrib.auth import authenticate,login,logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse,HttpResponseRedirect

# Create your views here.

def register(request):
    register=False
    if request.method=="POST":
        user_form=forms.User_Form(request.POST)
        user_data_form=forms.User_data_form(request.POST,request.FILES)
        if user_form.is_valid() and user_data_form.is_valid():
            user=user_form.save(commit=True)
            user.set_password(user.password)
            user.save()

            user_data=user_data_form.save(commit=False)
            user_data.user=user

            if 'profile_pic' in request.FILES:
                user_data.profile_pic=request.FILES['profile_pic']
            user_data.save()
            register=True
    else:
        user_form=forms.User_Form()
        user_data_form=forms.User_data_form()
    
    d={'form':user_data_form,'form_user':user_form,'register':register}
    return render(request,'app/register.html',context=d)

def index(request):
    user_name=request.session.get('username',"No User")
    return render(request,'app/base.html',context={'user_name':user_name})


def user_login(request):
    if request.method=="POST":
        username=request.POST.get('username',"")
        password=request.POST.get('password','')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                request.session['username']=username
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Not an Active user")
        else:
            print("Invalid Login")
            return HttpResponse("Invalid Login")
    else:
        return render(request,'app/login.html')

@login_required
def user_logout(request):
    logout(request)
    try:
        del request.session['username']
    except:
        pass
    return HttpResponseRedirect(reverse('index'))

@login_required
def wish(request):
    return HttpResponse("<h1>Hai Mr./Ms. {} </h1>".format(request.session['username']))

login_demo/templates/app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>HOME Page</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
  <span class="navbar-toggler-icon"></span>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
     <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'admin:index' %}">admin</li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:register'%}">signup</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'logout'%}">logout</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wish'%}">Wish</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'app:login'%}">login</a>
      </li>
      {% endif %}
      </ul>
</div>
</nav>
{% block body_block %}
<div class='jumbotron'>
<h1>Welcome to Homepage</h1>
{{user_name}} has loged in
</div>
{% endblock body_block %}
</body>
</html>

login_demo/templates/app/login.html
{% extends 'app/base.html' %}

{% block body_block %}
<div class="jumbotron">
<form action="{% url 'app:login' %}" method='POST'>
{% csrf_token %}
User_Name : <input type="text" name="username" placeholder="Enter User Name">
Password : <input type="password" name="password" placeholder="Enter Password">
<input type="submit" value="Upload">
</form>
</div>
{% endblock body_block %}

login_demo/templates/app/register.html
{% extends 'app/base.html' %}
{% block body_block %}
{% if register %}
<h1>Thanks for registering</h1>
{% else %}
<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form_user.as_p}}
{{form.as_p}}
<input type="submit" value="Upload">
</form>
{% endif %}
{% endblock body_block %}